#!/bin/bash
#
# opencode-kanban installer
#
# Usage:
#   ./install.sh          # install / update everything
#   ./install.sh --force  # overwrite existing agent files
#
# Prerequisites:
#   - Node.js >= 18
#   - opencode CLI (https://opencode.ai)
#   - opencode has been run at least once
#

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

# ── Resolve repo root ───────────────────────────────────────────

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
FORCE="${1:-}"

if [[ "$FORCE" == "--force" ]]; then
  info "Force mode: will overwrite existing agent files"
fi

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  opencode-kanban installer"
echo "═══════════════════════════════════════════════════════"
echo ""

# ── 1. Prerequisites ────────────────────────────────────────────

info "Checking prerequisites..."

# Detect Node.js
NODE_PATH=""
detect_node() {
  # Try sourcing nvm first
  if [ -s "$HOME/.nvm/nvm.sh" ]; then
    # shellcheck disable=SC1091
    source "$HOME/.nvm/nvm.sh" 2>/dev/null || true
  fi

  # Try various paths
  local candidates=(
    "$(command -v node 2>/dev/null)"
    "$HOME/.nvm/versions/node/$(ls "$HOME/.nvm/versions/node/" 2>/dev/null | sort -V | tail -1)/bin/node"
    "/opt/homebrew/bin/node"
    "/usr/local/bin/node"
    "/usr/bin/node"
  )

  for candidate in "${candidates[@]}"; do
    if [ -x "$candidate" ] 2>/dev/null; then
      NODE_PATH="$candidate"
      return 0
    fi
  done
  return 1
}

if ! detect_node || [ -z "$NODE_PATH" ]; then
  fail "Node.js not found. Install Node.js >= 18 first."
fi

# Check Node version >= 18
NODE_VERSION=$("$NODE_PATH" --version 2>/dev/null | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  fail "Node.js >= 18 required (found v${NODE_VERSION}). Upgrade Node.js."
fi
ok "Node.js v${NODE_VERSION} at ${NODE_PATH}"

# Check npm
NPM_PATH=""
if command -v npm &>/dev/null; then
  NPM_PATH="$(command -v npm)"
elif [ -x "$(dirname "$NODE_PATH")/npm" ]; then
  NPM_PATH="$(dirname "$NODE_PATH")/npm"
else
  fail "npm not found. Install npm."
fi
ok "npm at ${NPM_PATH}"

# Check opencode CLI
OPENCODE_PATH=""
if command -v opencode &>/dev/null; then
  OPENCODE_PATH="$(command -v opencode)"
elif [ -x "/opt/homebrew/bin/opencode" ]; then
  OPENCODE_PATH="/opt/homebrew/bin/opencode"
elif [ -x "/usr/local/bin/opencode" ]; then
  OPENCODE_PATH="/usr/local/bin/opencode"
else
  fail "opencode CLI not found. Install it from https://opencode.ai"
fi
ok "opencode at ${OPENCODE_PATH}"

# Check opencode has been run at least once
OPENCODE_DB="$HOME/.local/share/opencode/opencode.db"
if [ ! -f "$OPENCODE_DB" ]; then
  fail "opencode database not found at ${OPENCODE_DB}. Run 'opencode' at least once first."
fi
ok "opencode.db found"

OPENCODE_CONFIG="$HOME/.config/opencode"
mkdir -p "$OPENCODE_CONFIG"
mkdir -p "$OPENCODE_CONFIG/agents"

echo ""

# ── 2. Build ────────────────────────────────────────────────────

info "Building backend (npm install + tsc)..."
cd "$REPO_DIR"
BUILD_LOG=$(mktemp)
if ! "$NPM_PATH" install --production=false > "$BUILD_LOG" 2>&1; then
    cat "$BUILD_LOG"
    rm -f "$BUILD_LOG"
    fail "npm install failed"
fi
rm -f "$BUILD_LOG"
BUILD_LOG=$(mktemp)
if ! "$NPM_PATH" run build > "$BUILD_LOG" 2>&1; then
    cat "$BUILD_LOG"
    rm -f "$BUILD_LOG"
    fail "npm run build failed"
fi
rm -f "$BUILD_LOG"
if [ ! -f "$REPO_DIR/build/web.js" ]; then
    fail "Backend build failed — build/web.js not found"
fi
ok "Backend built"

info "Building frontend (web/)..."
cd "$REPO_DIR/web"
BUILD_LOG=$(mktemp)
if ! "$NPM_PATH" install > "$BUILD_LOG" 2>&1; then
    cat "$BUILD_LOG"
    rm -f "$BUILD_LOG"
    fail "npm install (frontend) failed"
fi
rm -f "$BUILD_LOG"
# Use vite build directly — tsc type-check can fail on shadcn components
# but vite compiles fine with esbuild
NPM_BIN="$(dirname "$NPM_PATH")"
BUILD_LOG=$(mktemp)
if ! "$NPM_BIN/npx" vite build > "$BUILD_LOG" 2>&1; then
    cat "$BUILD_LOG"
    rm -f "$BUILD_LOG"
    fail "vite build failed"
fi
rm -f "$BUILD_LOG"
if [ ! -f "$REPO_DIR/dist/web/index.html" ]; then
    fail "Frontend build failed — dist/web/index.html not found"
fi
ok "Frontend built"

cd "$REPO_DIR"
mkdir -p "$REPO_DIR/logs"
ok "Logs directory ready"

echo ""

# ── 3. Generate scripts/start-web.sh ────────────────────────────

info "Generating scripts/start-web.sh..."
  mkdir -p "$REPO_DIR/scripts"
  NODE_BIN_DIR="$(dirname "$NODE_PATH")"
  cat > "$REPO_DIR/scripts/start-web.sh" << SCRIPT
#!/bin/bash
# Auto-generated by install.sh — do not edit manually
export WEB_PORT="3210"
export DB_PATH="${REPO_DIR}/kanban.db"
export PATH="${NODE_BIN_DIR}:\$PATH"
exec ${NODE_PATH} ${REPO_DIR}/build/web.js
SCRIPT
chmod +x "$REPO_DIR/scripts/start-web.sh"
ok "scripts/start-web.sh generated"

echo ""

# ── 4. MCP Registration ────────────────────────────────────────

info "Registering kanban MCP server in opencode.json..."
OPENCODE_JSON="$OPENCODE_CONFIG/opencode.json"

"$NODE_PATH" -e "
const fs = require('fs');
const path = '$OPENCODE_JSON';
const nodePath = '$NODE_PATH';
const indexPath = '$REPO_DIR/build/index.js';

let config = {};
try {
  config = JSON.parse(fs.readFileSync(path, 'utf-8'));
} catch {
  config = { '\$schema': 'https://opencode.ai/config.json', permission: 'allow', mcp: {} };
}

config.mcp = config.mcp || {};
config.mcp.kanban = {
  type: 'local',
  command: [nodePath, indexPath],
  enabled: true
};

const tmp = path + '.tmp';
fs.writeFileSync(tmp, JSON.stringify(config, null, 2) + '\n');
fs.renameSync(tmp, path);
console.log('ok');
" || fail "Failed to update opencode.json"
ok "MCP server registered (command: ${NODE_PATH} ${REPO_DIR}/build/index.js)"

echo ""

# ── 5. Install Agents ──────────────────────────────────────────

info "Installing agent files..."

for agent in plan build ask builder; do
  SRC="$REPO_DIR/agents/${agent}.md"
  DST="$OPENCODE_CONFIG/agents/${agent}.md"

  if [ ! -f "$SRC" ]; then
    warn "  Source missing: $SRC"
    continue
  fi

  if [ -f "$DST" ] && [ "$FORCE" != "--force" ]; then
    echo -e "  ${YELLOW}⏭${NC}  Skipped ${agent}.md (already exists, use --force to overwrite)"
  else
    cp "$SRC" "$DST"
    if [ -f "$DST" ] && [ "$FORCE" != "--force" ]; then
      echo -e "  ${GREEN}✓${NC}  Written ${agent}.md"
    else
      echo -e "  ${GREEN}✓${NC}  Written ${agent}.md (overwritten)"
    fi
  fi
done

ok "Agent files installed"

echo ""

# ── 6. Install AGENTS.md ───────────────────────────────────────

info "Installing AGENTS.md (section merge)..."

AGENTS_MD="$OPENCODE_CONFIG/AGENTS.md"
TEMPLATE="$REPO_DIR/templates/AGENTS.md"

if [ ! -f "$TEMPLATE" ]; then
  fail "Template not found: $TEMPLATE"
fi

TEMPLATE_CONTENT=$(cat "$TEMPLATE")

"$NODE_PATH" -e "
const fs = require('fs');
const targetPath = '$AGENTS_MD';
const template = process.argv[1];

const MARKER_START = '<!-- opencode-kanban:start -->';
const MARKER_END = '<!-- opencode-kanban:end -->';
const newSection = fs.readFileSync(template, 'utf-8');

let existing = '';
try {
  existing = fs.readFileSync(targetPath, 'utf-8');
} catch {
  // File doesn't exist yet
}

if (existing.includes(MARKER_START)) {
  // Upgrade: replace existing section
  const regex = new RegExp(MARKER_START.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&') + '[\\\\s\\\\S]*?' + MARKER_END.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&'), 'm');
  const updated = existing.replace(regex, newSection.trim());
  const tmp = targetPath + '.tmp';
  fs.writeFileSync(tmp, updated);
  fs.renameSync(tmp, targetPath);
  console.log('updated');
} else {
  // First install: append section
  const content = (existing ? existing.trimEnd() + '\\n\\n' : '') + newSection.trim() + '\\n';
  const tmp = targetPath + '.tmp';
  fs.writeFileSync(tmp, content);
  fs.renameSync(tmp, targetPath);
  console.log('created');
}
" "$TEMPLATE" || fail "Failed to install AGENTS.md"

ok "AGENTS.md installed"

echo ""

# ── 7. launchd — Kanban Web Server (macOS) ─────────────────────

if [ "$(uname)" = "Darwin" ]; then
  info "Setting up launchd services..."

  LAUNCHD_DIR="$HOME/Library/LaunchAgents"
  mkdir -p "$LAUNCHD_DIR"

  # --- Kanban Web Server ---
  KANBAN_PLIST="$LAUNCHD_DIR/com.opencode-kanban.web.plist"

  info "  Generating com.opencode-kanban.web.plist..."
  cat > "$KANBAN_PLIST" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.opencode-kanban.web</string>
    <key>ProgramArguments</key>
    <array>
        <string>${REPO_DIR}/scripts/start-web.sh</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${REPO_DIR}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>${REPO_DIR}/logs/web-server.log</string>
    <key>StandardErrorPath</key>
    <string>${REPO_DIR}/logs/web-server.error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>WEB_PORT</key>
        <string>3210</string>
    </dict>
</dict>
</plist>
PLIST

  # Unload if already loaded, then load
  launchctl bootout "gui/$(id -u)/com.opencode-kanban.web" 2>/dev/null || true
  if ! launchctl bootstrap "gui/$(id -u)" "$KANBAN_PLIST" 2>/dev/null; then
    warn "  Failed to bootstrap web plist (may already be loaded or needs sudo)"
  fi
  ok "  com.opencode-kanban.web.plist loaded"

  # --- OpenCode Serve ---
  SERVE_PLIST="$LAUNCHD_DIR/com.opencode.serve.plist"

  info "  Generating com.opencode.serve.plist..."

  OPENCODE_DIR=$(dirname "$OPENCODE_PATH")
  NODE_BIN_DIR="$(dirname "$NODE_PATH")"
  # Build PATH that includes opencode's directory AND Node.js (nvm) directory
  PLIST_PATH="${NODE_BIN_DIR}:${OPENCODE_DIR}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

  cat > "$SERVE_PLIST" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.opencode.serve</string>
    <key>ProgramArguments</key>
    <array>
        <string>${OPENCODE_PATH}</string>
        <string>serve</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${HOME}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>${REPO_DIR}/logs/opencode-serve.log</string>
    <key>StandardErrorPath</key>
    <string>${REPO_DIR}/logs/opencode-serve.error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${PLIST_PATH}</string>
        <key>HOME</key>
        <string>${HOME}</string>
    </dict>
</dict>
</plist>
PLIST

  launchctl bootout "gui/$(id -u)/com.opencode.serve" 2>/dev/null || true
  if ! launchctl bootstrap "gui/$(id -u)" "$SERVE_PLIST" 2>/dev/null; then
    warn "  Failed to bootstrap opencode serve plist (may already be loaded or needs sudo)"
  fi
  ok "  com.opencode.serve.plist loaded"

  echo ""
else
  warn "Not macOS — skipping launchd setup."
  warn "Start services manually:"
  warn "  opencode serve &"
  warn "  $NODE_PATH $REPO_DIR/build/web.js"
  echo ""
fi

# ── 8. Verify ───────────────────────────────────────────────────

info "Verifying installation..."

sleep 5

ERRORS=0

# Check for port conflicts
for PORT in 3210 4096; do
    if lsof -i ":$PORT" -sTCP:LISTEN -P -n 2>/dev/null | grep -qv "node\|opencode" ; then
        warn "Port $PORT is in use by another process"
        lsof -i ":$PORT" -sTCP:LISTEN -P -n 2>/dev/null | head -3
    fi
done

# Check web server
if curl -sf -o /dev/null "http://localhost:3210/api/boards" 2>/dev/null; then
  ok "Web UI: http://localhost:3210"
else
  warn "Web UI not responding on :3210 (may still be starting...)"
  ERRORS=$((ERRORS + 1))
fi

# Check opencode serve
if curl -sf -o /dev/null "http://localhost:4096" 2>/dev/null; then
  ok "opencode serve: http://localhost:4096"
else
  warn "opencode serve not responding on :4096 (may still be starting...)"
  ERRORS=$((ERRORS + 1))
fi

# Check MCP registration
if grep -q '"kanban"' "$OPENCODE_JSON" 2>/dev/null; then
  ok "MCP server registered in opencode.json"
else
  fail "MCP server NOT found in opencode.json"
fi

echo ""
echo "═══════════════════════════════════════════════════════"
if [ $ERRORS -eq 0 ]; then
  echo -e "  ${GREEN}Installation complete!${NC}"
else
  echo -e "  ${YELLOW}Installation complete with warnings.${NC}"
  echo -e "  Services may need a few seconds to start."
fi
echo ""
echo "  Web UI:     http://localhost:3210"
echo "  Agents:     plan, build, ask, builder"
echo ""
echo "  To update:  git pull && ./install.sh"
echo "  To force:   ./install.sh --force"
echo "═══════════════════════════════════════════════════════"
echo ""
